CREATE TABLE [Statuses] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(50) NOT NULL UNIQUE,
  CONSTRAINT [PK_STATUSES] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Users] (
	Id int NOT NULL IDENTITY,
	Name nvarchar(50) NOT NULL,
	Login nvarchar(50) NOT NULL UNIQUE,
	Passw nvarchar(50) NOT NULL,
	Email nvarchar(50) NOT NULL UNIQUE,
  CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Tasks] (
	Id int NOT NULL IDENTITY,
	Title nvarchar(100) NOT NULL,
	About nvarchar(256) NOT NULL,
	Start date NOT NULL,
	Finish date NOT NULL,
	StatusId int NOT NULL,
	UserId int NOT NULL,
  CONSTRAINT [PK_TASKS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO


ALTER TABLE [Tasks] WITH CHECK ADD CONSTRAINT [Tasks_fk0] FOREIGN KEY ([StatusId]) REFERENCES [Statuses]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Tasks] CHECK CONSTRAINT [Tasks_fk0]
GO
ALTER TABLE [Tasks] WITH CHECK ADD CONSTRAINT [Tasks_fk1] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Tasks] CHECK CONSTRAINT [Tasks_fk1]
GO

